name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Go-Rod va automatiquement télécharger Chromium sous le capot, pas besoin d'installation complexe !
      # Sous Linux, il peut avoir besoin de quelques dépendances système :
      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2t64

      - name: Run E2E Tests
        run: go test ./cmd/server -v -run TestE2E
